// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpK39tC1d-IGScX5eO4PujR97KXh8TWqU',
    appId: '1:1093960089836:web:dddd231d1727c3c29225c9',
    messagingSenderId: '1093960089836',
    projectId: 'connect-final-199ec',
    authDomain: 'connect-final-199ec.firebaseapp.com',
    storageBucket: 'connect-final-199ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18j8-txhCOELUUm15rwr1jF5SONPTKHI',
    appId: '1:1093960089836:android:b6ac563e279e3a9e9225c9',
    messagingSenderId: '1093960089836',
    projectId: 'connect-final-199ec',
    storageBucket: 'connect-final-199ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrmSYsXDnoriQISQQMu8gEr_l-n96F7yI',
    appId: '1:1093960089836:ios:d2eee56f882a03b09225c9',
    messagingSenderId: '1093960089836',
    projectId: 'connect-final-199ec',
    storageBucket: 'connect-final-199ec.firebasestorage.app',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrmSYsXDnoriQISQQMu8gEr_l-n96F7yI',
    appId: '1:1093960089836:ios:8b04c8d86557b0589225c9',
    messagingSenderId: '1093960089836',
    projectId: 'connect-final-199ec',
    storageBucket: 'connect-final-199ec.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}